apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: smart-park

namespace: smart-park

resources:
- namespace.yaml
- api/
- auth/
- backend/
- bridge/
- web/
