apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: stolon

resources:
# RBAC stuff
# TODO(sandhose): split into multiple roles
- stolon-sa.yaml
- stolon-role.yaml
- stolon-rb.yaml
# Workloads
- init/
- keeper/
- sentinel/
- proxy/

secretGenerator:
- name: stolon
  literals:
  - su-password=Qhj01LzBugWr5YUt9YnwQieWk/k3UwASZzNp+ZJwf79wS+5CES7WED2FBMwlLEuM
  - repl-password=FDmveoMuRy7P5gYPOP33pX5PuyrnxZF1pTs4bCtvTNS2O4CiMpL/2lAOGagglP/1
