apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: nats

namespace: nats

resources:
- namespace.yaml
- serviceaccount.yaml
- service.yaml
- statefulset.yaml
# - servicemonitor.yaml TODO

configMapGenerator:
- name: nats
  files:
  - nats.conf
