---
apiVersion: v1
kind: Service
metadata:
  name: nats-mgmt
spec:
  clusterIP: None
  ports:
  - name: cluster
    port: 6222
    protocol: TCP
    targetPort: 6222
  - name: monitoring
    port: 8222
    protocol: TCP
    targetPort: 8222
  - name: metrics
    port: 7777
    protocol: TCP
    targetPort: 7777
---
apiVersion: v1
kind: Service
metadata:
  name: nats
spec:
  ports:
  - name: client
    port: 4222
    protocol: TCP
    targetPort: 4222
