apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: bridge
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bridge
  targetCPUUtilizationPercentage: 60
