apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/component: server

resources:
- serviceaccount.yaml
- role.yaml
- rolebinding.yaml
- statefulset.yaml
- service.yaml
- cluster-service.yaml

configMapGenerator:
- name: vault
  files:
  - config.hcl
