kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-agent-injector
subjects:
- kind: ServiceAccount
  name: injector
roleRef:
  kind: ClusterRole
  name: vault-agent-injector
  apiGroup: rbac.authorization.k8s.io
