apiVersion: apps/v1
kind: Deployment
metadata:
  name: stolon-proxy
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        component: stolon-proxy
        stolon-cluster: smart-park
    spec:
      serviceAccount: stolon
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels: {}
            topologyKey: kubernetes.io/hostname
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
      containers:
      - name: stolon-sentinel
        image: sandhose/stolon:latest
        imagePullPolicy: Always
        command:
        - stolon-proxy
        env:
        - name: STPROXY_CLUSTER_NAME
          value: "smart-park"
        - name: STPROXY_STORE_BACKEND
          value: "kubernetes"
        - name: STPROXY_KUBE_RESOURCE_KIND
          value: "configmap"
        - name: STPROXY_LISTEN_ADDRESS
          value: "0.0.0.0"
        - name: STPROXY_METRICS_LISTEN_ADDRESS
          value: "0.0.0.0:8080"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 8080
          name: metrics
        - containerPort: 5432
          name: pg
        readinessProbe:
          tcpSocket:
            port: pg
          initialDelaySeconds: 10
          timeoutSeconds: 5
