apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/component: proxy

resources:
- deployment.yaml
- service.yaml
- servicemonitor.yaml

configurations:
- ../../kustomizeconfig/servicemonitor.yaml
