apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: vault

namespace: vault

resources:
- server/
- injector/
- auth-serviceaccount.yaml
- auth-clusterrolebinding.yaml
