---
- name: install ssh keys for {{ ansible_user }}
  authorized_key:
    user: '{{ ansible_user }}'
    state: present
    key: '{{ item }}'
  with_file:
  - keys/constan.pub
  - keys/cyrille.pub
  - keys/sandhose.pub
  tags:
  - bootstrap

- name: setup sudo without password for {{ ansible_user }}
  template:
    src: 'sudoers.j2'
    dest: '/etc/sudoers.d/sudoers'
    mode: 0440
    validate: 'visudo -cf %s'
  tags:
  - bootstrap
  when: ansible_user != 'root'

- name: disable ssh password auth
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "PasswordAuthentication no"
    regexp: "^PasswordAuthentication"
  notify: reload sshd

- name: only allow {{ ansible_user }} to login via ssh
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "AllowUsers {{ ansible_user }}"
    regexp: "^AllowUsers"
  notify: reload sshd

- name: run apt update
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: create directory for persistent volumes
  file:
    path: /srv/data
    state: directory

- name: remove unecessary packages
  apt:
    pkg:
    - snap
    - lxcfs
    state: absent
