apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: bridge
spec:
  rules:
  - http:
      paths:
      - path: /api/v1/devices-push
        backend:
          serviceName: bridge
          servicePort: 80
