apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: web

resources:
- serviceaccount.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- hpa.yaml
