apiVersion: batch/v1
kind: Job
metadata:
  name: stolon-init
spec:
  template:
    spec:
      serviceAccount: stolon
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
      containers:
      - name: stolonctl
        image:  sandhose/stolon:latest
        imagePullPolicy: Always
        command:
        - "stolonctl"
        - "init"
        - "--cluster-name=smart-park"
        - "--store-backend=kubernetes"
        - "--kube-resource-kind=configmap"
        - "--yes"
        env:
        - name: STKEEPER_CLUSTER_NAME
          value: smart-park
        - name: STKEEPER_STORE_BACKEND
          value: "kubernetes"
        - name: STKEEPER_KUBE_RESOURCE_KIND
          value: "configmap"
      restartPolicy: OnFailure
