apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-requests-cpu: "40m"
        vault.hashicorp.com/agent-inject-secret-nats-ca.pem: "pki/issue/nats-client-auth"
        vault.hashicorp.com/agent-inject-template-nats-ca.pem: |
          {{ with secret "pki/issue/nats-client-auth" "common_name=auth" }}
          {{ .Data.issuing_ca }}{{ end }}
        vault.hashicorp.com/agent-inject-secret-nats-cert.pem: "pki/issue/nats-client-auth"
        vault.hashicorp.com/agent-inject-template-nats-cert.pem: |
          {{ with secret "pki/issue/nats-client-auth" "common_name=auth" }}
          {{ .Data.certificate }}{{ end }}
        vault.hashicorp.com/agent-inject-secret-nats-key.pem: "pki/issue/nats-client-auth"
        vault.hashicorp.com/agent-inject-template-nats-key.pem: |
          {{ with secret "pki/issue/nats-client-auth" "common_name=auth" }}
          {{ .Data.private_key }}{{ end }}
        vault.hashicorp.com/agent-inject-secret-providers.json: ""
        vault.hashicorp.com/agent-inject-template-providers.json: |
          {{- range $name := secrets "kv/metadata/tenants" -}}
            {{- with secret (printf "kv/data/tenants/%s" $name) -}}
              {{- scratch.MapSet "tenants" $name .Data.data -}}
            {{- end -}}
          {{- end -}}
          {{ scratch.Get "tenants" | toJSON }}
        vault.hashicorp.com/role: auth
    spec:
      serviceAccountName: auth
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchLabels: {}
              topologyKey: kubernetes.io/hostname
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
      containers:
      - name: auth
        image: m2smartpark/auth:latest
        imagePullPolicy: Always
        securityContext:
          readOnlyRootFilesystem: true
        env:
        - name: NATS_URL
          value: "nats://nats.nats.svc:4222"
        - name: NATS_CERT
          value: "/vault/secrets/nats-cert.pem"
        - name: NATS_KEY
          value: "/vault/secrets/nats-key.pem"
        - name: NATS_CA
          value: "/vault/secrets/nats-ca.pem"
        - name: PROVIDERS_CONFIG
          value: "/vault/secrets/providers.json"
        resources:
          requests:
            cpu: 50m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 50Mi
