FROM python:3.7-alpine
LABEL maintainer="Lionel Jung <lionel.jung@etu.unistra.fr>"

WORKDIR /app

# Install requirements
ADD requirements.txt ./
RUN apk add --no-cache -t .build gcc autoconf python3-dev musl-dev make openssl-dev && \
    pip install -r requirements.txt && \
    apk del --no-cache .build

# Add the rest
ADD . .

EXPOSE 8080

ENV PORT=8080
ENV HOST=0.0.0.0
ENV DEBUG=True

CMD ["python", "run.py"]
